/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/api/v1/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putTeam"];
        post?: never;
        delete: operations["deleteTeam"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/riders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putRider"];
        post?: never;
        delete: operations["deleteRider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putRace"];
        post?: never;
        delete: operations["deleteRace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/placements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putPlacement"];
        post?: never;
        delete: operations["deletePlacement"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putNation"];
        post?: never;
        delete: operations["deleteNation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putCup"];
        post?: never;
        delete: operations["deleteCup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTeams"];
        put?: never;
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/riders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRiders"];
        put?: never;
        post: operations["createRider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRaces"];
        put?: never;
        post: operations["createRace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlacements"];
        put?: never;
        post: operations["createPlacement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNations"];
        put?: never;
        post: operations["createNation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCups"];
        put?: never;
        post: operations["createCup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTeamsWithChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/riders/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRidersWithChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRacesWithChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/placements/rider/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlacementsByRider"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/placements/rider/{id}/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlacementsByRiderWithChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/placements/race/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlacementsByRace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/placements/race/{id}/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlacementsByRaceWithChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/placements/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlacementsWithChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nations/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNationsWithChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cups/nation/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCupsInNation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cups/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCupsWithChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        PutTeamDto: {
            teamName: string;
            shortName: string;
            teamDescription: string;
            /** Format: int64 */
            nationId: number;
        };
        GetTeamDto: {
            /** Format: int64 */
            id: number;
            teamName: string;
            shortName: string;
            teamDescription: string;
            /** Format: int64 */
            nationId: number;
            riderIds: number[];
        };
        PutRiderDto: {
            firstName: string;
            lastName: string;
            /** Format: date */
            dateOfBirth: string;
            /** Format: int64 */
            nationId: number;
            /** Format: int64 */
            teamId?: number;
        };
        GetRiderDto: {
            /** Format: int64 */
            id: number;
            firstName: string;
            lastName: string;
            /** Format: date */
            dateOfBirth: string;
            placementIds: number[];
            /** Format: int64 */
            nationId: number;
            /** Format: int64 */
            teamId?: number;
        };
        PutRaceDto: {
            raceName: string;
            /** Format: float */
            lengthInKm: number;
            /** Format: date */
            raceDate: string;
            /** Format: date-time */
            startTime: string;
            /** Format: int64 */
            nationId: number;
            /** Format: int64 */
            cupId?: number;
        };
        GetRaceDto: {
            /** Format: int64 */
            id: number;
            raceName: string;
            /** Format: float */
            lengthInKm: number;
            /** Format: date */
            raceDate: string;
            /** Format: date-time */
            startTime: string;
            /** Format: int64 */
            nationId: number;
            /** Format: int64 */
            cupId?: number;
            placementIds: number[];
        };
        PutPlacementDto: {
            /** Format: int32 */
            points: number;
            /** Format: int32 */
            finishTimeInSeconds: number;
            finishStatus: string;
            /** Format: int64 */
            riderId: number;
            /** Format: int64 */
            raceId: number;
        };
        GetPlacementDto: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            points: number;
            /** Format: int32 */
            finishTimeInSeconds: number;
            finishStatus: string;
            /** Format: int64 */
            riderId: number;
            /** Format: int64 */
            raceId: number;
        };
        PutNationDto: {
            longName: string;
            shortName: string;
            flagEmoji: string;
        };
        GetNationDto: {
            /** Format: int64 */
            id: number;
            longName: string;
            shortName: string;
            flagEmoji: string;
        };
        PutCupDto: {
            cupName: string;
            url?: string;
            /** Format: int64 */
            nationId: number;
        };
        GetCupDto: {
            /** Format: int64 */
            id: number;
            cupName: string;
            url?: string;
            raceIds: number[];
            /** Format: int64 */
            nationId: number;
        };
        PostTeamDto: {
            teamName: string;
            shortName: string;
            teamDescription: string;
            /** Format: int64 */
            nationId: number;
        };
        PostRiderDto: {
            firstName: string;
            lastName: string;
            /** Format: date */
            dateOfBirth: string;
            /** Format: int64 */
            nationId: number;
            /** Format: int64 */
            teamId?: number;
        };
        PostRaceDto: {
            raceName: string;
            /** Format: float */
            lengthInKm: number;
            /** Format: date */
            raceDate: string;
            /** Format: date-time */
            startTime: string;
            /** Format: int64 */
            nationId: number;
            /** Format: int64 */
            cupId?: number;
        };
        PostPlacementDto: {
            /** Format: int32 */
            points: number;
            /** Format: int32 */
            finishTimeInSeconds: number;
            finishStatus: string;
            /** Format: int64 */
            riderId: number;
            /** Format: int64 */
            raceId: number;
        };
        PostNationDto: {
            longName: string;
            shortName: string;
            flagEmoji: string;
        };
        PostCupDto: {
            cupName: string;
            url?: string;
            /** Format: int64 */
            nationId: number;
        };
        TeamFilter: {
            /** Format: int64 */
            id?: number;
            teamName?: string;
            shortName?: string;
        };
        PageGetTeamDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["GetTeamDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        PageableObject: {
            unpaged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            paged?: boolean;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
        };
        SortObject: {
            unsorted?: boolean;
            sorted?: boolean;
            empty?: boolean;
        };
        GetTeamWithChildrenDto: {
            /** Format: int64 */
            id: number;
            teamName: string;
            shortName: string;
            teamDescription: string;
            nation: components["schemas"]["NationDescriptorDto"];
            riders: components["schemas"]["RiderDescriptorDto"][];
        };
        NationDescriptorDto: {
            /** Format: int64 */
            id: number;
            longName: string;
            shortName: string;
            flagEmoji: string;
        };
        PageGetTeamWithChildrenDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["GetTeamWithChildrenDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        RiderDescriptorDto: {
            /** Format: int64 */
            id: number;
            firstName: string;
            lastName: string;
            /** Format: date */
            dateOfBirth: string;
        };
        RiderFilter: {
            /** Format: int64 */
            id?: number;
            firstName?: string;
            lastName?: string;
            /** Format: date */
            dateOfBirth?: string;
            /** Format: date */
            minDateOfBirth?: string;
            /** Format: date */
            maxDateOfBirth?: string;
        };
        PageGetRiderDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["GetRiderDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        GetRiderWithChildrenDto: {
            /** Format: int64 */
            id: number;
            firstName: string;
            lastName: string;
            /** Format: date */
            dateOfBirth: string;
            placements: components["schemas"]["PlacementDescriptorDto"][];
            nation: components["schemas"]["NationDescriptorDto"];
            team?: components["schemas"]["TeamDescriptorDto"];
        };
        PageGetRiderWithChildrenDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["GetRiderWithChildrenDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        PlacementDescriptorDto: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            points: number;
            /** Format: int32 */
            finishTimeInSeconds: number;
            finishStatus: string;
            /** Format: int64 */
            raceId: number;
        };
        TeamDescriptorDto: {
            /** Format: int64 */
            id: number;
            teamName: string;
            shortName: string;
            teamDescription: string;
        };
        RaceFilter: {
            /** Format: int64 */
            id?: number;
            raceName?: string;
            /** Format: float */
            lengthInKm?: number;
            /** Format: float */
            minLengthInKm?: number;
            /** Format: float */
            maxLengthInKm?: number;
            /** Format: date */
            raceDate?: string;
            /** Format: date */
            minRaceDate?: string;
            /** Format: date */
            maxRaceDate?: string;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            minStartTime?: string;
            /** Format: date-time */
            maxStartTime?: string;
        };
        PageGetRaceDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["GetRaceDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        CupDescriptorDto: {
            /** Format: int64 */
            id: number;
            cupName: string;
            url?: string;
        };
        GetRaceWithChildrenDto: {
            /** Format: int64 */
            id: number;
            raceName: string;
            /** Format: float */
            lengthInKm: number;
            /** Format: date */
            raceDate: string;
            /** Format: date-time */
            startTime: string;
            nation: components["schemas"]["NationDescriptorDto"];
            cup?: components["schemas"]["CupDescriptorDto"];
            placements: components["schemas"]["PlacementDescriptorDto"][];
        };
        PageGetRaceWithChildrenDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["GetRaceWithChildrenDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        PlacementFilter: {
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            points?: number;
            /** Format: int32 */
            minPoints?: number;
            /** Format: int32 */
            maxPoints?: number;
            /** Format: int32 */
            finishTimeInSeconds?: number;
            /** Format: int32 */
            minFinishTimeInSeconds?: number;
            /** Format: int32 */
            maxFinishTimeInSeconds?: number;
            finishStatus?: string;
        };
        PageGetPlacementDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["GetPlacementDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        GetPlacementWithChildrenDto: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            points: number;
            /** Format: int32 */
            finishTimeInSeconds: number;
            finishStatus: string;
            rider: components["schemas"]["RiderDescriptorDto"];
            race: components["schemas"]["RaceDescriptorDto"];
        };
        PageGetPlacementWithChildrenDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["GetPlacementWithChildrenDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        RaceDescriptorDto: {
            /** Format: int64 */
            id: number;
            raceName: string;
            /** Format: float */
            lengthInKm: number;
            /** Format: date */
            raceDate: string;
            /** Format: date-time */
            startTime: string;
        };
        NationFilter: {
            /** Format: int64 */
            id?: number;
            longName?: string;
            shortName?: string;
        };
        PageGetNationDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["GetNationDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        GetNationWithChildrenDto: {
            /** Format: int64 */
            id: number;
            longName: string;
            shortName: string;
            flagEmoji: string;
            riderIds: number[];
            cupIds: number[];
            raceIds: number[];
        };
        PageGetNationWithChildrenDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["GetNationWithChildrenDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        CupFilter: {
            /** Format: int64 */
            id?: number;
            cupName?: string;
        };
        PageGetCupDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["GetCupDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        GetCupWithChildrenDto: {
            /** Format: int64 */
            id: number;
            cupName: string;
            url?: string;
            races: components["schemas"]["RaceDescriptorDto"][];
            nation: components["schemas"]["NationDescriptorDto"];
        };
        PageGetCupWithChildrenDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["GetCupWithChildrenDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    putTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutTeamDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetTeamDto"];
                };
            };
        };
    };
    deleteTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    putRider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutRiderDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetRiderDto"];
                };
            };
        };
    };
    deleteRider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    putRace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutRaceDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetRaceDto"];
                };
            };
        };
    };
    deleteRace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    putPlacement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutPlacementDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetPlacementDto"];
                };
            };
        };
    };
    deletePlacement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    putNation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutNationDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetNationDto"];
                };
            };
        };
    };
    deleteNation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    putCup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutCupDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetCupDto"];
                };
            };
        };
    };
    deleteCup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTeams: {
        parameters: {
            query: {
                filter: components["schemas"]["TeamFilter"];
                page?: number;
                pageSize?: number;
                sortBy?: "TEAM_NAME" | "SHORT_NAME";
                sortDir?: "ASCENDING" | "DESCENDING";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGetTeamDto"];
                };
            };
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostTeamDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetTeamDto"];
                };
            };
        };
    };
    getRiders: {
        parameters: {
            query: {
                filter: components["schemas"]["RiderFilter"];
                page?: number;
                pageSize?: number;
                sortBy?: "FIRST_NAME" | "LAST_NAME" | "DATE_OF_BIRTH";
                sortDir?: "ASCENDING" | "DESCENDING";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGetRiderDto"];
                };
            };
        };
    };
    createRider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostRiderDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetRiderDto"];
                };
            };
        };
    };
    getRaces: {
        parameters: {
            query: {
                filter: components["schemas"]["RaceFilter"];
                page?: number;
                pageSize?: number;
                sortBy?: "RACE_NAME" | "LENGTH_IN_KM" | "RACE_DATE" | "START_TIME";
                sortDir?: "ASCENDING" | "DESCENDING";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGetRaceDto"];
                };
            };
        };
    };
    createRace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostRaceDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetRaceDto"];
                };
            };
        };
    };
    getPlacements: {
        parameters: {
            query: {
                filter: components["schemas"]["PlacementFilter"];
                page?: number;
                pageSize?: number;
                sortBy?: "POINTS" | "FINISH_TIME_IN_SECONDS" | "FINISH_STATUS";
                sortDir?: "ASCENDING" | "DESCENDING";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGetPlacementDto"];
                };
            };
        };
    };
    createPlacement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostPlacementDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetPlacementDto"];
                };
            };
        };
    };
    getNations: {
        parameters: {
            query: {
                filter: components["schemas"]["NationFilter"];
                page?: number;
                pageSize?: number;
                sortBy?: "LONG_NAME" | "SHORT_NAME";
                sortDir?: "ASCENDING" | "DESCENDING";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGetNationDto"];
                };
            };
        };
    };
    createNation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostNationDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetNationDto"];
                };
            };
        };
    };
    getCups: {
        parameters: {
            query: {
                filter: components["schemas"]["CupFilter"];
                page?: number;
                pageSize?: number;
                sortBy?: "CUP_NAME";
                sortDir?: "ASCENDING" | "DESCENDING";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGetCupDto"];
                };
            };
        };
    };
    createCup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCupDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetCupDto"];
                };
            };
        };
    };
    getTeamsWithChildren: {
        parameters: {
            query: {
                filter: components["schemas"]["TeamFilter"];
                page?: number;
                pageSize?: number;
                sortBy?: "TEAM_NAME" | "SHORT_NAME";
                sortDir?: "ASCENDING" | "DESCENDING";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGetTeamWithChildrenDto"];
                };
            };
        };
    };
    getRidersWithChildren: {
        parameters: {
            query: {
                filter: components["schemas"]["RiderFilter"];
                page?: number;
                pageSize?: number;
                sortBy?: "FIRST_NAME" | "LAST_NAME" | "DATE_OF_BIRTH";
                sortDir?: "ASCENDING" | "DESCENDING";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGetRiderWithChildrenDto"];
                };
            };
        };
    };
    getRacesWithChildren: {
        parameters: {
            query: {
                filter: components["schemas"]["RaceFilter"];
                page?: number;
                pageSize?: number;
                sortBy?: "RACE_NAME" | "LENGTH_IN_KM" | "RACE_DATE" | "START_TIME";
                sortDir?: "ASCENDING" | "DESCENDING";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGetRaceWithChildrenDto"];
                };
            };
        };
    };
    getPlacementsByRider: {
        parameters: {
            query: {
                filter: components["schemas"]["PlacementFilter"];
                page?: number;
                pageSize?: number;
                sortBy?: "POINTS" | "FINISH_TIME_IN_SECONDS" | "FINISH_STATUS";
                sortDir?: "ASCENDING" | "DESCENDING";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGetPlacementDto"];
                };
            };
        };
    };
    getPlacementsByRiderWithChildren: {
        parameters: {
            query: {
                filter: components["schemas"]["PlacementFilter"];
                page?: number;
                pageSize?: number;
                sortBy?: "POINTS" | "FINISH_TIME_IN_SECONDS" | "FINISH_STATUS";
                sortDir?: "ASCENDING" | "DESCENDING";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGetPlacementWithChildrenDto"];
                };
            };
        };
    };
    getPlacementsByRace: {
        parameters: {
            query: {
                filter: components["schemas"]["PlacementFilter"];
                page?: number;
                pageSize?: number;
                sortBy?: "POINTS" | "FINISH_TIME_IN_SECONDS" | "FINISH_STATUS";
                sortDir?: "ASCENDING" | "DESCENDING";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGetPlacementDto"];
                };
            };
        };
    };
    getPlacementsByRaceWithChildren: {
        parameters: {
            query: {
                filter: components["schemas"]["PlacementFilter"];
                page?: number;
                pageSize?: number;
                sortBy?: "POINTS" | "FINISH_TIME_IN_SECONDS" | "FINISH_STATUS";
                sortDir?: "ASCENDING" | "DESCENDING";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGetPlacementWithChildrenDto"];
                };
            };
        };
    };
    getPlacementsWithChildren: {
        parameters: {
            query: {
                filter: components["schemas"]["PlacementFilter"];
                page?: number;
                pageSize?: number;
                sortBy?: "POINTS" | "FINISH_TIME_IN_SECONDS" | "FINISH_STATUS";
                sortDir?: "ASCENDING" | "DESCENDING";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGetPlacementWithChildrenDto"];
                };
            };
        };
    };
    getNationsWithChildren: {
        parameters: {
            query: {
                filter: components["schemas"]["NationFilter"];
                page?: number;
                pageSize?: number;
                sortBy?: "LONG_NAME" | "SHORT_NAME";
                sortDir?: "ASCENDING" | "DESCENDING";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGetNationWithChildrenDto"];
                };
            };
        };
    };
    getCupsInNation: {
        parameters: {
            query: {
                filter: components["schemas"]["CupFilter"];
                page?: number;
                pageSize?: number;
                sortBy?: "CUP_NAME";
                sortDir?: "ASCENDING" | "DESCENDING";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGetCupDto"];
                };
            };
        };
    };
    getCupsWithChildren: {
        parameters: {
            query: {
                filter: components["schemas"]["CupFilter"];
                page?: number;
                pageSize?: number;
                sortBy?: "CUP_NAME";
                sortDir?: "ASCENDING" | "DESCENDING";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGetCupWithChildrenDto"];
                };
            };
        };
    };
}
